[package]
name = "html5ever-example"
version = "0.1.0"
authors = ["Joshua Nelson <jyn514@gmail.com>"]
edition = "2018"

[dependencies]
# change this to any version you like
html5ever = "0.24"
kuchiki = "0.8.0"
failure = "0.1"
